package nl.tue.ddss.bimsparql.geometry;

public enum GeometryType {
TYPE_POINT, TYPE_LINESTRING, TYPE_TRIANGLE, TYPE_POLYGON, TYPE_MULTIPOINT, TYPE_MULTILINESTRING, TYPE_MULTIPOLYGON, TYPE_GEOMETRYCOLLECTION, TYPE_TRIANGULATEDSURFACE, TYPE_POLYHEDRALSURFACE, TYPE_SOLID, TYPE_MULTISOLID
}
